[pytest]
addopts = -n auto --reruns 2 --alluredir=reports/allure-results
bdd_features_base_dir = features
markers =
    test1
    test2
    test3
    test4
    test5
    test6
    test7
    test8
    test9
    test10
    test15
    test16
    test18
    test19
    test20
    test25
    test36